### ISSUE TITLE
Cannot change layout

### ISSUE THREAD

**Issue by juliangorge** [samsonasik/ErrorHeroModule#89]
What ZF/Expressive/Laminas/Mezzio application I'm using when issue happen ?
- [X] Laminas 3

What PHP version you're using?
- [X] PHP 7.4

What ErrorHeroModule version you're using?
- [X] ^3.0

What Database you're using?
- [X] MySQL version ...

### Expected behavior
I'd like to change layout template file.

### Actual behavior
When I change 
'template' => [
   'layout' => 'layout/layout',

To: 

'template' => [
   'layout' => 'layout/error',

Does not change anything and it still call layout of my application

**Comment by samsonasik** [comment]
Layout is read defined config:

https://github.com/samsonasik/ErrorHeroModule/blob/17379158a3d0384db0b0871404f7b82715270a9c/src/Listener/Mvc.php#L124

So that's probably cache, did you run development-enable?

```
composer development-enable
```

And verify config cached in data/cache dir.

Ensure there is no duplicate config that override it.

**Comment by samsonasik** [comment]
If you follow the doc, it should work as is, no need to change other config, if you're using version 3.0.x, you need to follow readme from 3.0.x branch https://github.com/samsonasik/ErrorHeroModule/blob/3.x.x/README.md, that's it :)

If the issue persist, please provide failing test case, thank you.
